import pandas as pd
import warnings
warnings.filterwarnings('ignore')

data1 = pd.read_csv("D:/work/datasets/info/qrcode201901SUM_Info_10k.csv")
print("data1:" + str(data1.shape))
data2 = pd.read_csv("D:/work/datasets/info/qrcode201902SUM_Info_10k.csv")
print("data2:" + str(data2.shape))
data3 = pd.read_csv("D:/work/datasets/info/qrcode201903SUM_Info_10k.csv")
print("data3:" + str(data3.shape))
data4 = pd.read_csv("D:/work/datasets/info/qrcode201904SUM_Info_10k.csv")
print("data4:" + str(data4.shape))
data5 = pd.read_csv("D:/work/datasets/info/qrcode201905SUM_Info_10k.csv")
print("data5:" + str(data5.shape))
data6 = pd.read_csv("D:/work/datasets/info/qrcode201906SUM_Info_10k.csv")
print("data6:" + str(data6.shape))
data = pd.concat([data1,data2,data3,data4,data5,data6])
print("data:" + str(data.shape))

data["card_num"] = data["card_num"].map(lambda x : str(x))
data["user_id"] = data["user_id"].map(lambda x : str(x))
data["age"] = data["age"].map(lambda x : str(x))
data["paymentmethod"] = data["paymentmethod"].map(lambda x : str(x))
data["userid"] = data["userid"].map(lambda x : str(x))
data["credit_point_start_date"] = data["credit_point_start_date"].map(lambda x : str(x))
data["firstentry"] = data["firstentry"].map(lambda x : str(x))
data["business_date_str"] = data["business_date_str"].map(lambda x : str(x))
data['gender'] = data['gender'].astype('category')
data["month_xiaofei"] = data["credit_point_start_date"].str.slice(4,6)
data["business_date_str"] = pd.to_datetime(data["business_date_str"])
# data["exit_date_time_str"] = pd.to_datetime(data["exit_date_time_str"])
# data["entry_date_time_str"] = pd.to_datetime(data["entry_date_time_str"])

weather1 = pd.read_excel("D:/GitHub/datasets/weather of beijing/2019WeatherBJ.xlsx",sheet_name="1901")
weather2 = pd.read_excel("D:/GitHub/datasets/weather of beijing/2019WeatherBJ.xlsx",sheet_name="1902")
weather3 = pd.read_excel("D:/GitHub/datasets/weather of beijing/2019WeatherBJ.xlsx",sheet_name="1903")
weather4 = pd.read_excel("D:/GitHub/datasets/weather of beijing/2019WeatherBJ.xlsx",sheet_name="1904")
weather5 = pd.read_excel("D:/GitHub/datasets/weather of beijing/2019WeatherBJ.xlsx",sheet_name="1905")
weather6 = pd.read_excel("D:/GitHub/datasets/weather of beijing/2019WeatherBJ.xlsx",sheet_name="1906")

weatherJanJun = pd.concat([weather1,weather2,weather3,weather4,weather5,weather6])
weatherJanJun["date"] = pd.to_datetime(weatherJanJun["date"])
dfJanJun = pd.merge(data,weatherJanJun,how = "left",left_on="business_date_str",right_on="date")

dfJanJun.to_csv("D:/GitHub/datasets/qrcode_10k.csv",index=False)
print("完成")